BudgetAnalysisWeb/BudgetAnalysisWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', TemplateView.as_view(template_name='users/registration/home.html'), name='home'),
]

BudgetAnalysisWeb/users/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from users.views import *

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('login/', MyLoginView.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),

    path('confirm_email/',
         TemplateView.as_view(template_name='users/registration/confirm_email.html'),
         name='confirm_email'),

    path('verify_email/<uidb64>/<token>/',
         EmailVerify.as_view(),
         name='verify_email'),

    path('invalid_verify/',
         TemplateView.as_view(template_name='users/registration/invalid_verify.html'),
         name='invalid_verify'),

    path('', main, name='main'),
    path('profile/', profile_view, name='profile'),

    path('categories/', category_list, name='category_list'),
    path('categories/create/', category_create, name='category_create'),
    path('categories/<int:category_id>/edit/', category_edit, name='category_edit'),
    path('categories/<int:category_id>/delete/', category_delete, name='category_delete'),

    path('accounts/', accounts, name='accounts'),
    path('accounts/create/', create_account, name='create_account'),
    path('accounts/<int:account_id>/edit/', edit_account, name='edit_account'),
    path('accounts/delete/<int:account_id>/', delete_account, name='delete_account'),

    path('transfer/', transfer, name='transfer'),
]

BudgetAnalysisWeb/users/models.py
import os

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.files import File
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save

from BudgetAnalysisWeb.settings import AUTH_USER_MODEL
from users.validators import positive_number_validator


class User(AbstractUser):
    email = models.EmailField(
        _('email address'),
        unique=True,
    )

    email_verify = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']


class UserDataModel(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    surname = models.CharField(max_length=100, blank=True)
    patronymic = models.CharField(max_length=100, blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True)
    sex = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return f"{self.name}: {self.user}"


class CategoryModel(models.Model):
    EXPENSES = 'Расходы'
    INCOME = 'Доходы'
    CATEGORY_TYPE_CHOICES = (
        (EXPENSES, 'Расходы'),
        (INCOME, 'Доходы'),
    )
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=100, blank=True)
    key = models.CharField(max_length=100, choices=CATEGORY_TYPE_CHOICES, default=EXPENSES, blank=True)
    icon = models.ImageField(upload_to='users/static/images/')

    def __str__(self):
        return f"{self.category_name}: {self.user}"


class Account(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    balance = models.DecimalField(max_digits=10, decimal_places=2)
    icon = models.ImageField(upload_to='users/static/images/')

    def __str__(self):
        return f"{self.name}"


class Transaction(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    from_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='sent_transactions')
    to_account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='received_transactions')
    amount = models.DecimalField(max_digits=10, decimal_places=2, validators=[positive_number_validator])
    date = models.DateField(default=timezone.now, editable=True)
    comment = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.from_account} -> {self.to_account}: {self.amount}"


def create_default_categories(sender, instance, created, **kwargs):
    if created:
        if CategoryModel.objects.filter(user=instance).count() == 0:
            default_categories_expenses = [
                {'name': 'Кафе и рестораны', 'icon': 'users/static/images/icon1.jpeg'},
                {'name': 'Одежда и аксессуары', 'icon': 'users/static/images/icon2.jpeg'},
                {'name': 'Красота и здоровье', 'icon': 'users/static/images/icon3.jpeg'},
                {'name': 'Продукты', 'icon': 'users/static/images/icon4.jpeg'},
                {'name': 'Все для дома', 'icon': 'users/static/images/icon5.jpeg'},
                {'name': 'Транспорт', 'icon': 'users/static/images/icon1.jpeg'},
                {'name': 'Развлечения', 'icon': 'users/static/images/icon2.jpeg'},
                {'name': 'Обязательные платежи', 'icon': 'users/static/images/icon3.jpeg'},
                {'name': 'Переводы', 'icon': 'users/static/images/icon4.jpeg'},
                {'name': 'Другое', 'icon': 'users/static/images/icon5.jpeg'}
            ]
            default_categories_revenues = [
                {'name': 'Зарплата', 'icon': 'users/static/images/icon1.jpeg'},
                {'name': 'Стипендия', 'icon': 'users/static/images/icon2.jpeg'},
                {'name': 'Социальные выплаты', 'icon': 'users/static/images/icon3.jpeg'},
                {'name': 'Проценты по вкладу', 'icon': 'users/static/images/icon4.jpeg'},
                {'name': 'Переводы', 'icon': 'users/static/images/icon5.jpeg'},
                {'name': 'Другое', 'icon': 'users/static/images/icon5.jpeg'}
            ]

            for category_data in default_categories_expenses:
                category = CategoryModel(user=instance, category_name=category_data['name'], key='Расходы')
                icon_path = os.path.join(settings.MEDIA_ROOT, category_data['icon'])
                with open(icon_path, 'rb') as f:
                    category.icon.save(os.path.basename(icon_path), File(f), save=True)
                category.save()

            for category_data in default_categories_revenues:
                category = CategoryModel(user=instance, category_name=category_data['name'], key='Доходы')
                icon_path = os.path.join(settings.MEDIA_ROOT, category_data['icon'])
                with open(icon_path, 'rb') as f:
                    category.icon.save(os.path.basename(icon_path), File(f), save=True)
                category.save()


post_save.connect(create_default_categories, sender=AUTH_USER_MODEL)

BudgetAnalysisWeb/users/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import (
    UserCreationForm as DjangoUserCreationForm,
    AuthenticationForm as DjangoAuthenticationForm,
)
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from users.models import UserDataModel, CategoryModel, Account, Transaction
from users.utils import send_email_for_verify

User = get_user_model()


class AuthenticationForm(DjangoAuthenticationForm):

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(self.request, username=username, password=password)

            if not self.user_cache.email_verify:
                send_email_for_verify(self.request, self.user_cache)
                raise ValidationError('Ваш почта не верифицирована, проверьте ее', code='invalid_login')

            if self.user_cache is None:
                raise self.get_invalid_login_error()

            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UserCreationFormImpl(DjangoUserCreationForm):

    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ('username', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserDataModel
        fields = ('name', 'surname', 'patronymic', 'date_of_birth', 'phone', 'sex')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserProfileForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        user_profile = super().save(commit=False)
        if self.request and self.request.user:
            user_profile.user = self.request.user
        if commit:
            user_profile.save()
        return user_profile


class CategoryForm(forms.ModelForm):
    class Meta:
        model = CategoryModel
        fields = ('category_name', 'key', 'icon')


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'balance', 'icon']


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['from_account', 'to_account', 'amount', 'date', 'comment']

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

BudgetAnalysisWeb/users/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.exceptions import ValidationError
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.tokens import default_token_generator as \
    token_generator
from users.forms import AuthenticationForm, UserCreationFormImpl, UserProfileForm, CategoryForm, TransactionForm, \
    AccountForm
from users.models import UserDataModel, CategoryModel, Account
from users.utils import send_email_for_verify

User = get_user_model()


class MyLoginView(LoginView):
    form_class = AuthenticationForm


class EmailVerify(View):
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user)
            return redirect('main')
        return redirect('invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


class Register(View):
    template_name = 'users/registration/register.html'

    def get(self, request):
        context = {
            'form': UserCreationFormImpl()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationFormImpl(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=password)
            send_email_for_verify(request, user)
            return redirect('confirm_email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


def main(request):
    return render(request, 'profile/main.html')


@login_required
def profile_view(request):
    user_profile, created = UserDataModel.objects.get_or_create(user=request.user)
    form = UserProfileForm(instance=user_profile)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    return render(request, 'profile/profile.html', {'form': form})


@login_required
def edit_profile_view(request):
    user_profile, created = UserDataModel.objects.get_or_create(user=request.user)
    form = UserProfileForm(instance=user_profile)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
    return render(request, 'profile/edit_profile.html', {'form': form})


@login_required
def category_list(request):
    categories = CategoryModel.objects.filter(user=request.user)
    context = {
        'categories': categories,
    }
    return render(request, 'profile/categories/category_list.html', context)


@login_required
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            category = form.save(commit=False)
            category.user = request.user
            category.save()
            return redirect('category_list')
    else:
        form = CategoryForm()
    context = {
        'form': form
    }
    return render(request, 'profile/categories/category_form.html', context)


@login_required
def category_edit(request, category_id):
    category = get_object_or_404(CategoryModel, id=category_id, user=request.user)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            category = form.save()
            return redirect('category_list')
    else:
        form = CategoryForm(instance=category)
    context = {
        'form': form,
        'category': category
    }
    return render(request, 'profile/categories/category_form.html', context)


@login_required
def category_delete(request, category_id):
    category = get_object_or_404(CategoryModel, id=category_id, user=request.user)
    category.delete()
    return redirect('category_list')


def accounts(request):
    accounts = Account.objects.filter(user=request.user)
    return render(request, 'profile/accounts/accounts.html', {'accounts': accounts})


def create_account(request):
    if request.method == 'POST':
        form = AccountForm(request.POST, request.FILES)
        if form.is_valid():
            account = form.save(commit=False)
            account.user = request.user
            account.save()
            return redirect('accounts')
    else:
        form = AccountForm()
    return render(request, 'profile/accounts/create_account.html', {'form': form})


def edit_account(request, account_id):
    account = get_object_or_404(Account, id=account_id)
    if request.method == 'POST':
        form = AccountForm(request.POST, instance=account)
        if form.is_valid():
            form.save()
            return redirect('accounts')
    else:
        form = AccountForm(instance=account)
    return render(request, 'profile/accounts/edit_account.html', {'form': form, 'account': account})


def delete_account(request, account_id):
    account = Account.objects.get(id=account_id)
    account.delete()
    return redirect('accounts')


@login_required
def transfer(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            from_account = form.cleaned_data['from_account']
            to_account = form.cleaned_data['to_account']
            amount = form.cleaned_data['amount']
            date = form.cleaned_data['date']
            comment = form.cleaned_data['comment']
            user = request.user # текущий пользователь
            if from_account.balance >= amount:  # Check if the sender has enough funds
                from_account.balance -= amount
                from_account.save()
                to_account.balance += amount
                to_account.save()
                transaction = form.save(commit=False)
                transaction.user = user
                transaction.save()
                return redirect('accounts')
            else:
                form.add_error('from_account', 'Недостаточно средств на счете для осуществления перевода')
    else:
        form = TransactionForm()
    return render(request, 'profile/accounts/transfer.html', {'form': form})

BudgetAnalysisWeb/users/templates/users/profile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styleUserProfile.css' %}">
  {% block title %}
  {% endblock %}
</head>
<body>
  <header>
    <div id="title"><h1>SmartMoney</h1></div>
    <div class="column-profile-notifications">
      <div class="search">
        <h3>
          <form action="" method="get">
            <input class="name-search" name="search" placeholder="Поиск" type="search">
            <input type="image" src="/static/images/search-image.png" class="button-search" name="submit">
          </form>
        </h3>
        <div class="search-line"></div>
      </div>
      <div class="noti-profile">
        <div class="notification-list">
          <img class="notification-image"  src="/static/images/notification-image.png"/>
        </div>
        <div class="profile-list">
          <a href="{% url 'profile' %}">
            <img class="profile-image" src="/static/images/ava.png"/>
          </a>
        </div>
      </div>
    </div>
  </header>

  {% block content %}
  {% endblock %}


    <footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>

        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="#">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>
    {% block footer %}
  {% endblock %}

</body>
</html>

BudgetAnalysisWeb/users/templates/users/profile/categories.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/styleCategory.css' %}">
    <title>Категории</title>
</head>
<body>



<footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>
        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="#">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>

</body>
</html>

BudgetAnalysisWeb/users/templates/users/profile/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styleMain.css' %}">

    <title>Главная</title>

</head>
<body>
  <header>
    <div id="title"><h1>SmartMoney</h1></div>
    <div class="column-profile-notifications">
      <div class="search">
        <h3>
          <form action="" method="get">
            <input class="name-search" name="search" placeholder="Поиск" type="search">
            <input type="image" src="/static/images/search-image.png" class="button-search" name="submit">
          </form>
        </h3>
        <div class="search-line"></div>
      </div>
      <div class="noti-profile">
        <div class="notification-list">
          <img class="notification-image"  src="/static/images/notification-image.png"/>
        </div>
        <div class="profile-list">
          <a href="{% url 'profile' %}">
            <img class="profile-image" src="/static/images/ava.png"/>
          </a>
        </div>
      </div>
    </div>
  </header>


  <div class="container">
    <div class="vertical-menu">
        <a href="{% url 'main' %}">Главная</a>
        <a href="{% url 'accounts' %}">Счета</a>
        <a href="#">Статистика</a>
        <a href="{% url 'category_list' %}">Категории</a>
        <a href="#">Настройки</a>
    </div>


    <div class="f-block">
      <div class="name-blocks">
              <select class="name-categories">
                  <option>Все счета</option>
                  <option>Зарплатная карта</option>
                  <option>Кредитная карта</option>
                  <option>Тинькофф</option>
              </select>
          <div class="add-operation">Добавить операцию</div>
              <select class="period-choice">
                  <option>Месяц</option>
                  <option>День</option>
                  <option>Неделя</option>
                  <option>Год</option>
              </select>
          <input type="date" class="start-period" name="calendar">
          <input type="date" class="end-period" name="calendar">
      </div>
    <div class="block-left">

        <div class="operations-history">
            <div class="title-container">История операций</div>
        </div>
    </div>
    <div class="block-right">
        <div class="block-right-top">
            <div class="expenses">
                <div class="title-container">Расходы</div>
            </div>
        </div>
        <div class="block-right-bottom">
            <div class="income">
                <div class="title-container">Доходы</div>
            </div>
        </div>
    </div>
  </div>
</div>


    <footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>

        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="#">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>


</body>
</html>

BudgetAnalysisWeb/users/templates/users/profile/profile.html
{% extends 'users/profile/base.html' %}

{% block title %}
{% endblock %}

{% block content %}

<div class="container">
  <div class="user-info">
      <div class="avatar">
        <img class="avatar-image" src="/static/images/ava.png"/>
      </div>
      <div class="user-name">
        <form>
          <h2>{{ form.name }} {{ form.surname }}</h2>
        </form>
      </div>
  </div>

  <form method="post">
    {% csrf_token %}
      <div id="profile-form">
        <div class="content-form">
          <div class="profile-form">
            <div class="row">
              <div class="row-item-one">
                <div class="row-item-one-left">
                  <label>Email</label>
                  <input type="text"
                         class="login"
                         required placeholder="{{ user }}" readonly>
                </div>
                <div class="row-item-two-left">
                  <label for="id_name">Имя</label>
                  <input name="name"
                         id="id_name"
                         type="text"
                         class="name"
                         required placeholder="Имя"
                         value="{{ form.name.value }}">
                </div>
                <div class="row-item-three-left">
                  <label for="id_surname">Фамилия</label>
                  <input name="surname"
                         id="id_surname"
                         type="text"
                         class="surname"
                         required placeholder="Фамилия"
                         value="{{ form.surname.value }}">
                </div>
                <div class="row-item-four-left">
                  <label for="id_surname">Отчество</label>
                  <input name="patronymic"
                         id="id_patronymic"
                         type="text"
                         class="patronymic"
                         placeholder="Отчество"
                         value="{{ form.patronymic.value }}">
                </div>
              </div>
              <div class="row-item-two">
                <div class="row-item-one-right">
                  <label>Логин</label>
                  <input type="text" class="login" required placeholder={{ user.username }} readonly>
                </div>
                <div class="row-item-two-right">
                  <label for="id_date_of_birth">Дата рождения</label>
                  <input name="date_of_birth"
                         id="id_date_of_birth"
                         type="date"
                         class="birthdate"
                         placeholder="{{ form.date_of_birth.label }}"
                         value="{{ form.date_of_birth.value|date:'Y-m-d' }}">
                </div>
                <div class="row-item-three-right">
                  <label for="id_phone">Телефон</label>
                  <input name="phone"
                         id="id_phone"
                         type="text"
                         class="phone"
                         placeholder="Пример: +78005353535"
                         value="{{ form.phone.value }}">
                </div>
                <div class="row-item-four-right">
                  <label for="id_sex">Пол</label>
                  <input name="sex"
                         id="id_sex"
                         type="text"
                         class="sex"
                         placeholder="Мужской/Женский"
                         value="{{ form.sex.value }}">
                </div>
              </div>
            </div>
            <div class="btn"><button class="button-red" type="submit"><a>Сохранить</a></button></div>
          </div>
        </div>
      </div>
    </form>
  </div>


  {% block footer %}
    <footer>
    <div class="footer">
      <div class="footer-title">
        <a href="{% url 'main' %}" class="home-link">SmartMoney</a>
      </div>

        <ul class="list-menu-footer">
          <li>
            <a class="nav-link" href="{% url 'main' %}">Главная</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'accounts' %}">Счета</a>
          </li>
          <li>
            <a class="nav-link" href="#">Статистика</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'category_list' %}">Категории</a>
          </li>
          <li>
            <a class="nav-link" href="#">Настройки</a>
          </li>
          <li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
            {% endif %}
          </li>
        </ul>
      <ul class="feedback">
        <li>Если появились вопросы, свяжитесь с нами</li>
        <li>E-mail: ratshackers@mail.ru</li>
      </ul>
    </div>
  </footer>
  {% endblock %}

{% endblock %}